import { NextRequest, NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";

async function kvGet(key: string): Promise<string | null> {
  const url = process.env.UPSTASH_REDIS_REST_URL;
  const token = process.env.UPSTASH_REDIS_REST_TOKEN;
  if (!url || !token) return null;
  const res = await fetch(`${url}/get/${encodeURIComponent(key)}`, {
    headers: { Authorization: `Bearer ${token}` },
  });
  const data = (await res.json()) as { result: string | null };
  return data.result;
}

async function kvSet(key: string, value: string): Promise<void> {
  const url = process.env.UPSTASH_REDIS_REST_URL;
  const token = process.env.UPSTASH_REDIS_REST_TOKEN;
  if (!url || !token) return;
  await fetch(
    `${url}/set/${encodeURIComponent(key)}/${encodeURIComponent(value)}`,
    { method: "POST", headers: { Authorization: `Bearer ${token}` } }
  );
}

export async function POST(req: NextRequest) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { squareItemId, imageUrl } = (await req.json()) as {
      squareItemId: string;
      imageUrl: string;
    };

    if (!squareItemId || !imageUrl) {
      return NextResponse.json(
        { error: "Missing squareItemId or imageUrl" },
        { status: 400 }
      );
    }

    // Get user's Square OAuth token
    const oauthRaw = await kvGet(`user:${userId}:square_oauth`);
    if (!oauthRaw) {
      return NextResponse.json(
        { error: "Square not connected" },
        { status: 400 }
      );
    }

    const oauth = JSON.parse(oauthRaw);
    const accessToken = oauth.accessToken;

    // Download the image
    const imgRes = await fetch(imageUrl);
    if (!imgRes.ok) {
      return NextResponse.json(
        { error: "Failed to download image" },
        { status: 502 }
      );
    }
    const imageBuffer = Buffer.from(await imgRes.arrayBuffer());

    // Upload to Square as CatalogImage
    const idempotencyKey = `${userId}-${squareItemId}-${Date.now()}`;
    const requestJson = JSON.stringify({
      idempotency_key: idempotencyKey,
      object_id: squareItemId,
      image: {
        type: "IMAGE",
        id: `#plateai-${squareItemId}`,
        image_data: {
          name: `PlateAI photo for ${squareItemId}`,
          caption: "Generated by PlateAI",
        },
      },
    });

    // Build multipart form data
    const boundary = `----PlateAIBoundary${Date.now()}`;
    const parts: Buffer[] = [];

    // JSON part
    parts.push(
      Buffer.from(
        `--${boundary}\r\nContent-Disposition: form-data; name="request"\r\nContent-Type: application/json\r\n\r\n${requestJson}\r\n`
      )
    );

    // Image part
    parts.push(
      Buffer.from(
        `--${boundary}\r\nContent-Disposition: form-data; name="image_file"; filename="photo.jpg"\r\nContent-Type: image/jpeg\r\n\r\n`
      )
    );
    parts.push(imageBuffer);
    parts.push(Buffer.from(`\r\n--${boundary}--\r\n`));

    const body = Buffer.concat(parts);

    const uploadRes = await fetch(
      "https://connect.squareup.com/v2/catalog/images",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": `multipart/form-data; boundary=${boundary}`,
        },
        body,
      }
    );

    const uploadData = await uploadRes.json();

    if (!uploadRes.ok) {
      console.error("Square image upload error:", uploadData);
      return NextResponse.json(
        { error: "Failed to upload image to Square" },
        { status: 502 }
      );
    }

    const squareImageId = uploadData.image?.id;

    // Update catalog item status in KV
    const catalogRaw = await kvGet(`user:${userId}:catalog`);
    if (catalogRaw) {
      const catalog = JSON.parse(catalogRaw);
      const updated = catalog.map(
        (item: { squareItemId: string; plateaiImageUrl?: string; status?: string }) => {
          if (item.squareItemId === squareItemId) {
            return { ...item, plateaiImageUrl: imageUrl, status: "synced" };
          }
          return item;
        }
      );
      await kvSet(`user:${userId}:catalog`, JSON.stringify(updated));
    }

    return NextResponse.json({ success: true, squareImageId });
  } catch (error) {
    console.error("Push image error:", error);
    return NextResponse.json(
      { error: "Failed to push image to Square" },
      { status: 500 }
    );
  }
}
